#!/usr/bin/env bash
# Original build script provided by WaterfallMC.

upstream=Flick
upstream_branch=main
downstream=fantasia

case "$1" in
    "rb" | "rbp" | "rebuild")
        scripts/rebuildPatches.sh "$upstream" "$downstream" || exit 1
    ;;
    "p" | "patch")
        (git submodule update --init
	scripts/applyPatches.sh "$upstream" "$downstream" "$upstream_branch") || exit 1
    ;;
    "m" | "up" | "merge")
        scripts/mergeUpstream.sh "$upstream" "$upstream_branch" || exit 1
    ;;
    "b" | "build")
        (git submodule update --init
	scripts/applyPatches.sh "$upstream" "$downstream" "$upstream_branch"
        cd $downstream
        # build commands here
        flutter pub get
	rm -f pubspec.lock
        flutter pub upgrade --major-versions
	sed -i "s/FLICK_SED_HERE/$(git -C ../Flick rev-parse --short HEAD)/" \
		lib/core/constants/app_constants.dart
	sed -i "s/FANTASIA_SED_HERE/$(git rev-parse --short HEAD)/" \
		lib/core/constants/app_constants.dart
	if [ -n "$KPLOC" ] ; then
            mv "$KPLOC" android/key.properties
	    mv "$KLOC" android/"$KSLOC"
	    ( [ ! -f android/key.properties ] || \
	      [ ! -f android/"$KSLOC" ] ) && exit 72
	fi
        cd rust && cargo fetch \
		--target "aarch64-linux-android" \
		--target "armv7-linux-androideabi" \
		--target "x86_64-linux-android" \
		&& cd ..
        flutter build apk --release --split-per-abi --target-platform=android-arm64 || exit 36
	cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/"$downstream"-"$(date '+%y%m%d-%H%M%S')"-arm64.apk
        cd ..) || exit 1
    ;;
    *)
        echo "Commands:"
        echo "  * rb, rbp, rebuild | Rebuilds the patches"
        echo "  * p, patch         | Applies all the patches to Velocity"
        echo "  * m, up, merge     | Utility to aid in merging upstream"
        echo "  * b, build         | Builds the project"
    ;;
esac
