name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
        steps:
            - uses: actions/checkout@v7
            - name: configure
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  sudo apt update && sudo apt upgrade
                  sudo apt install libc6-dev build-essential
            - name: patch
              run: |
                  ./patchwork p
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: stable
            - name: build
              run: |
                  ./patchwork b
            - name: catch them all
              run: |
                  find . -iname '*.apk'
            - name: Upload a build artifact
              uses: actions/upload-artifact@v7
              with:
                name: idk lbruh
                path: fantasia/app/build/outputs/apk/debug/app-debug.apk
