name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
        steps:
            - uses: actions/checkout@v7
            - name: configure
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  sudo apt update
                  sudo apt install libc6-dev gcc-multilib
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
            - name: something
              env:
                KST: ${{ secrets.KST }}
                KPROP: ${{ secrets.KPROP }}
                KLOC: ${{ secrets.KLOC }}
                KPLOC: ${{ secrets.KPLOC }}
              run: |
                  echo "$KST" | base64 -d > "$KLOC"
                  echo "$KPROP" | base64 -d > "$KPLOC"
                  a="$(du -b "$KPLOC" | cut -d'	' -f1 )"
                  [ "$a" -lt 1 ] && exit 1
            - name: build
              env:
                KPLOC: ${{ secrets.KPLOC }}
                KLOC: ${{ secrets.KLOC }}
                KSLOC: ${{ secrets.KSLOC }}
              run: ./pw b
            - name: no
              if: always()
              env:
                KLOC: ${{ secrets.KLOC }}
                KSLOC: ${{ secrets.KSLOC }}
              run: shred -fzu fantasia/android/app/"$KSLOC" fantasia/android/key.properties
            - uses: actions/upload-artifact@v7
              with:
                path: fantasia/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
                archive: false
                if-no-files-found: error
            - name: analyze
              run: |
                  cd fantasia
                  flutter analyze || :
                  flutter pub outdated || :
