name: build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
        steps:
            - uses: actions/checkout@v7
            - name: configure
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  sudo apt install libc6-dev build-essential gcc-multilib
            - name: patch
              run: |
                  ./patchwork p
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: stable
            - name: build
              run: |
                  ./patchwork b
            - uses: actions/upload-artifact@v7
              with:
                name: abcd
                path: fantasia/build/app/outputs/flutter-apk/app-release.apk
